### ISSUE TITLE
Ralph integration

### ISSUE THREAD

**Issue by vi4m** [dankraw/ssh-aliases#21]
It could be even more automatic to populate hosts from Ralph CMDB, based on user hosts ownership.

**Comment by dankraw** [comment]
Hi Marcin :) It's a good idea, I was already thinking about providing some kind of integration with a data-source that knows about hosts a user has access to. I think that such interface could be quite abstract and Ralph would be a great plug-in implementation example.

This project (ssh-aliases) was meant to be a simple command line tool that allowed me to generate a number of aliases for hosts that shared a common naming pattern. The most irritating thing about preparing templates for ssh-aliases is getting to know how many hosts of what I have on a specific environment, and then putting those numbers in (of course the numbers change with time, so it's even worse). You just do this once for a while, but still, it would be great to simply make a request and fill all those templates with real life hosts.

I'm not sure if that's what you meant as I'm not an expert in Ralph, but what I'm thinking is:

1. query Ralph (let's say `/api/my-hosts/`) -> it returns a list of hosts `["host1.dev.example.com", "host1.test.example.com", "host2.test.example.com", ...]`
2. I have some kind of a template that matches a group of returned hosts (`host<n>.<env>.example.com`)
3. Aliases are generated, the configs are applied etc.

Does Ralph have any other useful data that would be useful for ssh aliases generation that I'm not aware of?

**Comment by dankraw** [comment]
I just realeased [v0.3.0](https://github.com/dankraw/ssh-aliases/releases/tag/v0.3.0) with a feature of generating aliases using regular expressions matching over provided input list of hostnames (that could be generated using Ralph API, or any other). In my opinion this feature fulfills the idea introduced here.
