### ISSUE TITLE
Hostnames that start with a _ are seemed as invalid

### ISSUE THREAD

**Issue by igorhrcek** [dankraw/ssh-aliases#29]
https://github.com/dankraw/ssh-aliases/blob/54034079d2a1a40000b23ca8d8e2f79136ac852f/compiler/expander.go#L21

I have a hostname called `_something.domain.com`, it is sort of special  subdomain name that starts with a `_`, but I cannot compile the `config` because of this regexp.

**Comment by dankraw** [comment]
hi @igorhrcek, thanks for the issue.
You are right, the underscore should be allowed here. I should fix this soon.

**Comment by dankraw** [comment]
@igorhrcek hi, I've just fixed it and released as v0.3.2, I hope it works for you. :]
