### ISSUE TITLE
Multiple aliases

### ISSUE THREAD

**Issue by peacememories** [dankraw/ssh-aliases#31]
Hi, thank you very much for developing this useful tool!
One small feature I've been missing is the ability to specify multiple aliases (which would, I guess, expand to multiple host definitions). I haven't found anything about this in the docs, so I'm assuming it doesn't exist yet. It would be great for defining multiple names for a server (like, the name of the host, as well as the service that provides it, which is my usecase)
Thanks for considering! :)

**Comment by dankraw** [comment]
Hi, I'm happy to hear you find this tool useful. :)
When it comes to the feature request, I believe what you are looking for is possible to achieve already, please look at the second bullet in the tips and tricks (alias can accept multiple space separated entries):
https://github.com/dankraw/ssh-aliases#tips-and-tricks

**Comment by peacememories** [comment]
Ah, seems I missed that! I tried with commas but that didn't work. This works perfectly for me :)
Thanks for the quick reply!
